# Generated by Django 3.1.2 on 2021-08-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(default='creator,stuff', max_length=300),
        ),
    ]
